version: "3"

volumes:
  mongodata:
    driver: local

services:
  app:
    container_name: lyrical-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:4000"
    networks:
      - backend
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_DATABASE: lyrical
      MONGO_PORT: 27017

  mongo:
    image: mongo:4.4
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
